# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false
after_success:
  - Rscript -e 'covr::codecov()'
addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal
      - libfftw3-dev
      - cargo
      - python3-dev
      - python3-pip
      - python3-virtualenv
      - python3-venv
before_script:
  - python3 -m pip install --upgrade --ignore-installed --user travis virtualenv
  - R -e 'install.packages("tensorflow")'
  - R -e 'tensorflow::install_tensorflow(version = "1.14.0", extra_packages=c("IPython", "tensorflow-probability"))'
  - R -e 'tensorflow::tf_config()'
